# Generated by Django 3.0.6 on 2020-05-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomagam_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.IntegerField(choices=[(1, 'fundacja'), (2, 'organizacja pozarządowa'), (3, 'zbiórka lokalna'), (4, 'domyślnie fundacja')]),
        ),
    ]
