# Generated by Django 3.0.6 on 2020-05-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomagam_app', '0003_auto_20200516_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='pick_up_date',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pick_up_time',
            field=models.CharField(max_length=6),
        ),
    ]
