# Generated by Django 3.0.6 on 2020-05-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomagam_app', '0005_auto_20200516_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.IntegerField(choices=[(1, 'Fundacja'), (2, 'Organizacja pozarządowa'), (3, 'Zbiórka lokalna'), (4, 'Domyślnie fundacja')]),
        ),
    ]
